import type { Detection, Machine, Summary } from '@/types';
import { MACHINE_ID } from './constants';

const now = Date.now();
const minutesAgo = (minutes: number) => new Date(now - minutes * 60_000).toISOString();

export const mockDetections: Detection[] = [
  {
    eventId: `${MACHINE_ID}-DEMO-0008`,
    machineId: MACHINE_ID,
    deviceModel: 'Jetson Nano B01 + ESP32-S3 N16R8',
    detectedType: 'plastic_bottle',
    confidence: 0.94,
    targetBin: 'bin_1',
    sortCommand: 'SORT_BIN_1',
    sortingStatus: 'success',
    createdAt: minutesAgo(2),
    serverReceivedAt: minutesAgo(2),
  },
  {
    eventId: `${MACHINE_ID}-DEMO-0007`,
    machineId: MACHINE_ID,
    deviceModel: 'Jetson Nano B01 + ESP32-S3 N16R8',
    detectedType: 'aluminum_can',
    confidence: 0.89,
    targetBin: 'bin_2',
    sortCommand: 'SORT_BIN_2',
    sortingStatus: 'success',
    createdAt: minutesAgo(8),
    serverReceivedAt: minutesAgo(8),
  },
  {
    eventId: `${MACHINE_ID}-DEMO-0006`,
    machineId: MACHINE_ID,
    deviceModel: 'Jetson Nano B01 + ESP32-S3 N16R8',
    detectedType: 'paper_carton',
    confidence: 0.83,
    targetBin: 'bin_3',
    sortCommand: 'SORT_BIN_3',
    sortingStatus: 'success',
    createdAt: minutesAgo(15),
    serverReceivedAt: minutesAgo(15),
  },
  {
    eventId: `${MACHINE_ID}-DEMO-0005`,
    machineId: MACHINE_ID,
    deviceModel: 'Jetson Nano B01 + ESP32-S3 N16R8',
    detectedType: 'plastic_bottle',
    confidence: 0.91,
    targetBin: 'bin_1',
    sortCommand: 'SORT_BIN_1',
    sortingStatus: 'success',
    createdAt: minutesAgo(23),
    serverReceivedAt: minutesAgo(23),
  },
  {
    eventId: `${MACHINE_ID}-DEMO-0004`,
    machineId: MACHINE_ID,
    deviceModel: 'Jetson Nano B01 + ESP32-S3 N16R8',
    detectedType: 'unknown_object',
    confidence: 0.52,
    targetBin: 'unknown_bin',
    sortCommand: 'SORT_UNKNOWN',
    sortingStatus: 'unknown',
    createdAt: minutesAgo(34),
    serverReceivedAt: minutesAgo(34),
  },
  {
    eventId: `${MACHINE_ID}-DEMO-0003`,
    machineId: MACHINE_ID,
    deviceModel: 'Jetson Nano B01 + ESP32-S3 N16R8',
    detectedType: 'aluminum_can',
    confidence: 0.86,
    targetBin: 'bin_2',
    sortCommand: 'SORT_BIN_2',
    sortingStatus: 'success',
    createdAt: minutesAgo(48),
    serverReceivedAt: minutesAgo(48),
  },
  {
    eventId: `${MACHINE_ID}-DEMO-0002`,
    machineId: MACHINE_ID,
    deviceModel: 'Jetson Nano B01 + ESP32-S3 N16R8',
    detectedType: 'plastic_bottle',
    confidence: 0.78,
    targetBin: 'bin_1',
    sortCommand: 'SORT_BIN_1',
    sortingStatus: 'failed',
    createdAt: minutesAgo(61),
    serverReceivedAt: minutesAgo(61),
  },
  {
    eventId: `${MACHINE_ID}-DEMO-0001`,
    machineId: MACHINE_ID,
    deviceModel: 'Jetson Nano B01 + ESP32-S3 N16R8',
    detectedType: 'paper_carton',
    confidence: 0.81,
    targetBin: 'bin_3',
    sortCommand: 'SORT_BIN_3',
    sortingStatus: 'success',
    createdAt: minutesAgo(82),
    serverReceivedAt: minutesAgo(82),
  },
];

export const mockSummary: Summary = {
  machineId: MACHINE_ID,
  total: 128,
  byType: {
    plastic_bottle: 62,
    aluminum_can: 38,
    paper_carton: 21,
    unknown_object: 7,
  },
  byBin: {
    bin_1: 62,
    bin_2: 38,
    bin_3: 21,
    unknown_bin: 7,
  },
  avgConfidence: 0.88,
  successRate: 0.92,
};

export const mockMachine: Machine = {
  machineId: MACHINE_ID,
  name: 'Smart Bin Prototype 01',
  location: 'GreenGuard Demo Lab',
  hardware: {
    edgeComputer: 'Jetson Nano B01',
    controller: 'ESP32-S3 N16R8',
  },
  currentState: 'SORTING',
  lastEventId: mockDetections[0].eventId,
  lastSeenAt: minutesAgo(1),
  recentHeartbeats: [
    { machineId: MACHINE_ID, state: 'SORTING', lastEventId: mockDetections[0].eventId, createdAt: minutesAgo(1) },
    { machineId: MACHINE_ID, state: 'SYNCING', lastEventId: mockDetections[1].eventId, createdAt: minutesAgo(6) },
    { machineId: MACHINE_ID, state: 'IDLE', lastEventId: mockDetections[2].eventId, createdAt: minutesAgo(12) },
    { machineId: MACHINE_ID, state: 'SORTING', lastEventId: mockDetections[3].eventId, createdAt: minutesAgo(21) },
  ],
};
